apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argo-cd

spec:
  project: default
  source:
    repoURL: https://github.com/kunish/website.git
    targetRevision: HEAD
    path: cicd
  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
