apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: website
  namespace: argo-cd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: personal website

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
