name: Build & Publish Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  image: kunish/website

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.image }}
          tags: |
            type=sha
            type=edge

      - uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
