name: Build & Publish Docker Image

on:
  push:
    branches: [main]

env:
  image: kunish/website

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install

      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - run: echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - run: echo ${{ env.tag }}

      - uses: docker/build-push-action@v2
        with:
          tags: ${{ env.image }}:${{ env.tag }}
          push: true
